# Generated by Django 5.2.7 on 2025-11-10 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadedPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('download_date', models.DateTimeField(auto_now_add=True)),
                ('tracks_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloaded_playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Скачанный плейлист',
                'verbose_name_plural': 'Скачанные плейлисты',
                'ordering': ['-download_date'],
            },
        ),
        migrations.CreateModel(
            name='DownloadedTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('artist', models.CharField(max_length=500)),
                ('file_path', models.CharField(max_length=1000)),
                ('file_size', models.BigIntegerField(default=0, help_text='Размер файла в байтах')),
                ('format', models.CharField(default='mp3', max_length=10)),
                ('bitrate', models.IntegerField(blank=True, help_text='Битрейт в kbps', null=True)),
                ('downloaded_playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music_downloader.downloadedplaylist')),
            ],
            options={
                'verbose_name': 'Скачанный трек',
                'verbose_name_plural': 'Скачанные треки',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yandex_playlist_id', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('track_count', models.IntegerField(default=0)),
                ('preview_loaded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Плейлист',
                'verbose_name_plural': 'Плейлисты',
                'unique_together': {('user', 'yandex_playlist_id', 'owner')},
            },
        ),
        migrations.AddField(
            model_name='downloadedplaylist',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music_downloader.playlist'),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yandex_track_id', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('artist', models.CharField(max_length=500)),
                ('duration', models.IntegerField(blank=True, help_text='Длительность в секундах', null=True)),
                ('position', models.IntegerField(default=0)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music_downloader.playlist')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yandex_token', models.CharField(blank=True, help_text='OAuth токен Yandex Music', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
            },
        ),
    ]
